### ISSUE TITLE
Backend service call failure is not leading the delivery to end up in compensation queue

### ISSUE THREAD

**Issue by kirpasingh** [mspnp/microservices-reference-implementation#92]
If a backend service call fails, delivery along with metadata should end up in compensation queue. However it's not happening though you can see the error messages in the logs.

**Comment by ferantivero** [comment]
ping

**Comment by kirpasingh** [comment]
PR #99 assigned to @cfarre fixes this. On his plate for a while now but due to other commitments, he didn't get time to review and close it.

**Comment by cfarre** [comment]
@kirpasingh 
the PR that fixes this problem contains the following issues
1.artifactId>wiremock-standalone,system-rules and wiremock-body-transformer in pom.xml are causing an interception on every single call to services causing a significant capacity/scale decrease. 
2. there is not warranty that CloudQueueClient is thread safe make it instance in superviseFailureAsync
3. remove  queueReference.createIfNotExists() from superviseFailureAsync and put it in Main since this is anti-pattern even for exception path
